#!/bin/bash
Version="v2021-06-11"
MYNAME=`whoami`
SUFFIX=osconfig
docker_registry=mynas24.dynu.net:5433/ezos

install_to_system()
{
    if [ "$MYNAME" = "root" ];then
        echo "Please run as non root user"
        exit 0
    fi
    
    git_server=`git config --get remote.origin.url`
    name=`basename $git_server`
    #remove .git
    name=${name%.git}
    
    if [ -L $0 ];then
        scriptname=`readlink $0 | xargs basename`
    else
	      scriptname=`realpath $0 | xargs basename`
    fi
    
    echo "This program will install to ~/.local/$name"
    read -p "Do you wish to install this program[yes/no]?" yn
    if [ "$yn" != "yes" ];then
      echo "abort install"
      exit 0
    fi
    
    if [ -L ~/.local/bin/$scriptname ];then
        echo "Error!!This program seem already install"
        read -p "Force to install[yes/no]?" yn
        if [ "$yn" != "yes" ];then
          echo "abort install"
          exit 0
        fi
        rm -rf ~/.local/bin/$scriptname ~/.local/$name
    fi
    
    mkdir -p ~/.local/bin
    git -C ~/.local/ clone $git_server $name
    ln -sf ~/.local/$name/$scriptname ~/.local/bin/
    ls ~/.local/$name/
    if [ -f ~/.local/$name/$scriptname.bash_complete ];then
        echo "do link"
        sudo ln -sf ~/.local/$name/$scriptname.bash_complete /etc/bash_completion.d/$scriptname.bash_complete
    fi
    echo "install success!!"
}

if [ "$1" = "install" ];then
  install_to_system
fi

get_dir()
{
    if [ -L $0 ];then
        src_dir=`readlink $0 | xargs dirname`
    else
	      src_dir=`realpath $0 | xargs dirname`
    fi
    config_dir=$src_dir/configs
}
get_dir

if [ ! -f  $src_dir/scripts/cmd.head.sh ] || [ ! -f  $src_dir/scripts/cmd.tail.sh ];then
    echo "cmd.head.sh or cmd.tail.sh not found"
    exit 99
fi

. $src_dir/scripts/cmd.head.sh

##local function#####
env_check()
{
    if [ "$MYNAME" = "root" ];then
        echo "Please run as non root user"
        exit 0
    fi
    if [ -f /.dockerenv ];then
        echo "please run on host OS"
        exit 0
    fi
 
    docker -v &>/dev/null
    if [ "$?" != "0" ];then
        echo "docker is not install"
        echo "Refrernce to https://docs.docker.com/install/linux/docker-ce/ubuntu/ to install docker"
        exit 0
    fi
}

instance_not_exist()
{
    XX=`docker ps -a -q -f name=$1`
    if [ "$XX" = "" ];then
      #echo "dkos $ins_name is already exist"
      return 0
    fi
    return 1
}
image_not_exist()
{
   hd_ins=`docker image ls $image_base -q`
   if [ "$hd_ins" = "" ];then
     return 0
   fi
   return 1

}
load_config()
{
    local lerror=0
    if [ -z $1 ];then
	    error_out "error project name"
    fi
    
    if [ "$config_loaded" = "1" ];then
	    return
    fi

    local config=${config_dir}/${1}.${SUFFIX}
    if [ ! -f $config ];then
	    error_out "config file not found"
    fi
    . $config
    if [ -z $EZBV_name ];then
      EZBV_name=${1}
	    echo "Warning:EZBV_name not found,use file name"
    fi
    if [ -z $EZBV_image ];then
      echo "Error:EZBV_image not found"
      lerror=1
    fi
    [ $lerror -eq 1 ] && error_out "config file parameter error"
    config_loaded=1

}
create_docker_os()
{
    local pro=$1
    load_config $pro

    if image_not_exist $EZBV_image ;then
        docker pull $EZBV_image
    fi
    if instance_not_exist $EZBV_name ;then
        VOPTION=""
        VOPTION+=" -v /etc/passwd:/etc/passwd:ro -v /etc/shadow:/etc/shadow:ro -v /etc/group:/etc/group:ro"
        VOPTION+=" -v$HOME:$HOME"
        VOPTION+=" --restart=always"
        VOPTION+=" $EZBV_extra_opt"
	#echo "docker run -idt --hostname $EZBV_name --name $EZBV_name $VOPTION $EZBV_image"
        docker run -idt --hostname $EZBV_name --name $EZBV_name $VOPTION $EZBV_image
    else
	    echo "$EZBV_name already exist!! Continue......"
    fi

}
##############################init###############################################
env_check
##########################MAIN cmd function#######################################
cmd_version()
{
    echo "=========Last commit==============="
    git -C "$src_dir" log -1
    echo "=========version: $Version==============="
}
help_add "version" "version - show version."
cmd_update()
{
    local pro=$1
    git -C $src_dir pull 
    if [ -z "$pro" ];then
        echo "update list success."
        exit 0
    fi
    load_config $pro
    docker stop $EZBV_name &>/dev/null
    docker rm $EZBV_name &>/dev/null
    docker pull $EZBV_image
    echo "update $pro done.Please login $pro again to take effect!!"
}
help_add "update" "update osname - update OS's config/image"

cmd_ls()
{
    osname=$1
    file=${config_dir}/${osname}.${SUFFIX}
    if [ -f $file ];then
        echo "==================================="
    		echo "$name"
    		cat $file
        return
    fi
    
    detail=$1
    lists=`ls ${config_dir}/*.${SUFFIX}`
    for list in $lists;do
	    name=`basename $list | cut -f1 -d "."`
    	if [ ! -z $detail ];then
    		echo "==================================="
    		echo "$name"
    		cat $list
    	else
    		echo "$name"
    	fi
    done
}
help_add "list" "ls [ osname ] - list supported OS"

cmd_del()
{
    local pro=$1
    load_config $pro
    docker stop $EZBV_name &>/dev/null
    docker rm $EZBV_name &>/dev/null
    echo "Delete $pro finish!!"
}
help_add "del" "del osname - del running os."
cmd_login()
{
    local pro=$1
    load_config $pro
    
    #create os first.
    create_docker_os $pro
    
    if [ "$EZBV_islinux32" != "" ];then
	    dolinux32=linux32
    else
	    dolinux32=
    fi

    local ins_name=$EZBV_name
    if [ "$ins_name" = "" ];then
        error_out "EZBV_name is empty!!"
    fi
    if [ "$EZBV_shell" != "" ];then
	    myshell=$EZBV_shell
    else
	    if docker exec -it $ins_name ls /bin/bash &>/dev/null ;then
	        myshell="/bin/bash"
	    elif docker exec -it $ins_name ls /bin/ash  &>/dev/null ;then
	        myshell="/bin/ash"
	    else
	        myshell="/bin/sh"
	    fi
    fi
    if [ "$2" = "root" ] ;then
        echo "login $ins_name as root"
        docker exec -it $ins_name  $dolinux32 $myshell

        #eval "docker exec -it $ins_name $dolinux32 $myshell -c '$extra_cmd cd $PWD&&su -s $myshell root'"
    else
        MTNAME=`whoami`
        shift 1
        if [ "$1" != "" ];then
            extra_cmd="$@;"
        fi

        #docker exec -it $ins_name su - $MYNAME
        #echo "docker exec -it $ins_name /bin/sh -c 'cd $PWD&&su $MYNAME'"

        echo "login $ins_name as $MYNAME"
        eval "docker exec -it $ins_name $dolinux32 $myshell -c '$extra_cmd cd $PWD&&su -s $myshell $MYNAME'"

    fi
}
help_add "login" "login osname - login os."

cmd_save()
{
    local pro=$1
    local pushnow=$2
    create_docker_os $pro

    if [ "$EZBV_image" = "" ];then
        echo "error parameter"
        return
    fi    
    
    echo "Image save to $EZBV_image"
    docker commit $EZBV_name $EZBV_image
    if [ ! -z "$pushnow" ];then
        echo "Push docker image $EZBV_image"
        docker push $EZBV_image
    fi
}
help_add "save" "save osname [ pushnow ]- save os and push to docker registy"

cmd_push()
{
    local pro=$1

    create_docker_os $pro

    if [ "$2" != "" ];then
        EZBV_image=$2
    fi

    if [ "$EZBV_name" = "" ];then
        echo "error parameter"
        return
    fi    
    
    echo "Image save to $EZBV_image"
    docker commit $EZBV_name $EZBV_image
    if [ ! -z "$pushnow" ];then
        echo "Push docker image $EZBV_image"
        docker push $EZBV_image
    fi
}
#all use simple help.
rename_fn help_show old_help_show

help_show()
{
    echo "Valid argument:"
    echo "  version - show version"
    echo "  ls [ osname ] - list supported OS"
    echo "  update osname - update OS's config/image"
    echo "  login osname [ root ]  - login OS "
    echo "  install - install to system "
}
cmd_help()
{
  help_show
}
help_add "help" "help - show commands"

cmd_help2()
{
   old_help_show
}
help_add "help2" "help2 - show all help"

cmd_dev_newos()
{
    local name=$1
    local src_docker=$2
    local repo=$docker_registry/${name}-ezbbuild-img
    local option="$3"
    local myshell=$4
    if [ -f  ${config_dir}/${name}.${SUFFIX} ];then
        error_out "Error!! $name already exist!!"
    fi
    
    if [ "$name" = "" ] || [ "$src_docker" = "" ];then
	    error_out "Error parameter"
    fi
    echo "pull docker image $src_docker"
    docker pull $src_docker || error_out "docker pull $src_docker fail"
    docker tag $src_docker $repo || error_out "docker tag fail"
    echo "create config file ${config_dir}/${name}.${SUFFIX}"
    cat << EOF > ${config_dir}/${name}.${SUFFIX}
EZBV_image=$repo
EZBV_name=${name}-benv
EZBV_extra_opt="$option"
EZBV_shell=$myshell
EOF
}
help_add "dev_newos" "dev newos - name src_docker docker_options [shell ] - create new OS"

cmd_dev_save()
{
    local name=$1
    local pushnow=$2

    do_cmd "git -C $src_dir add ${config_dir}/${name}.${SUFFIX}"
    do_cmd "git -C $src_dir commit -m \"devel_save by $MYNAME\""

    load_config $name
    do_cmd "docker commit $EZBV_name $EZBV_image"
    if [ ! -z "$pushnow" ];then 
        git -C $src_dir push
	echo "docker push $EZBV_image"
        do_cmd "docker push $EZBV_image"
    fi
}
help_add "dev_save" "dev save osname [ pushnow ] - save config/images and push to server!"
cmd_dev_clean()
{
    local name=$1
    if [ -z "$name" ];then
        git -C  $src_dir reset --hard origin/master
        rm -rf ${config_dir}/*
        git -C  $src_dir checkout -- ${config_dir}
        echo "Done"
        exit 0
    fi

    load_config $name
    docker stop $EZBV_name &>/dev/null
    docker rm $EZBV_name &>/dev/null
    do_cmd "rm -f ${config_dir}/${name}.${SUFFIX}"
    echo "Delete $name Done"
    git -C  $src_dir checkout -- .
}
help_add "dev_clean" "dev clean osname - delete develop os config "

help_add "push" "push osname - push to docker registry"

. $src_dir/scripts/cmd.tail.sh

